### ISSUE TITLE
README.md show a non valid example

### ISSUE THREAD

**Issue by Maxioum** [Maxioum/Peeler#4]
In the readme it is said that running `peeler manifest` with this pyproject create a `blender_manifest.toml`.

```toml
# pyproject.toml

[project]
name = "my_awesome_addon"
version = "1.0.0"
```

But it throw a ValidationError:

```bash
ValidationError: The pyproject must contain a [`tool.peeler`] table. 
```
