### ISSUE TITLE
Update uv release workflow

### ISSUE THREAD

**Issue by Maxioum** [Maxioum/Peeler#40]
- add a link to the uv changelog pinned to specific release such as : https://github.com/astral-sh/uv/blob/main/CHANGELOG.md#0611 and/or add its content to the PR body
- if there is already an open PR, update it instead of creating a new one
- make workflow run daily instead of weekly

**Comment by Maxioum** [comment]
- It might be preferable not to restrict the maximum `uv` version.  
- Run the same workflow and only apply a restriction if the tests fail.  
- And apply the restriction by default only for **major** version changes. 


In .max-uv-version:
```
0.6.*
```

in pyproject.toml
```toml
[project.optional-dependencies]
uv = [
    "uv >= 0.5.17",
    "uv == 0.6.*" # or uv == 0.*
]
```
